SIMU = {
    "SuperPredateur": {
        "nb": 2,
        "vitesseMin": 1,
        "vitesseMax": 5,
        "AccMin" : 1,
        "AccMAx" : 10,
        "MinFaim" : 1,
        "MaxFaim" : 10,
        "MinFatigue": 1,
        "MaxFatigue": 10,
        "MinRepro": 1,
        "MaxRepro": 10,
        "MinEsp": 1,
        "MaxEsp": 10,
    },
    "Carnivore": {
        "nb": 2,
        "vitesseMin": 1,
        "vitesseMax": 5,
        "AccMin": 1,
        "AccMAx": 10,
        "MinFaim": 1,
        "MaxFaim": 10,
        "MinFatigue": 1,
        "MaxFatigue": 10,
        "MinRepro": 1,
        "MaxRepro": 10,
        "MinEsp": 1,
        "MaxEsp": 10,
    },
    "Decomposeur": {
        "nb": 2,
        "vitesseMin": 1,
        "vitesseMax": 5,
        "AccMin": 1,
        "AccMAx": 10,
        "MinFaim": 1,
        "MaxFaim": 10,
        "MinFatigue": 1,
        "MaxFatigue": 10,
        "MinRepro": 1,
        "MaxRepro": 10,
        "MinEsp": 1,
        "MaxEsp": 10,
    },
    "Herbivore": {
        "nb": 2,
        "vitesseMin": 1,
        "vitesseMax": 5,
        "AccMin": 1,
        "AccMAx": 10,
        "MinFaim": 1,
        "MaxFaim": 10,
        "MinFatigue": 1,
        "MaxFatigue": 10,
        "MinRepro": 1,
        "MaxRepro": 10,
        "MinEsp": 1,
        "MaxEsp": 10,
    },

}